# Jupyter ipython

In [1]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [4]:
list?

In [5]:
?len

In [6]:
L = [1, 2, 3]

In [7]:
L.insert?

In [8]:
L?

In [9]:
def square(a):
    """return square of a """
    return a ** 2

In [10]:
square??

In [11]:
len??

TAB Bottom и shift + tab подсказки

In [12]:
L.sort()

In [13]:
from os import path
from os import curdir

shift + tab

In [14]:
path.exists(".")

True

magic command<br>
% - one string<br>
%% - all cell

In [15]:
s = 0
% time for i in range(0, 1000000): s = s + i

CPU times: user 140 ms, sys: 0 ns, total: 140 ms
Wall time: 143 ms


In [16]:
%%time
s = 0
for i in range(0, 1000000): s = s + i

CPU times: user 125 ms, sys: 0 ns, total: 125 ms
Wall time: 127 ms


In [17]:
%%timeit
s = 0
for i in range(0, 1000000): s = s + i

65.9 ms ± 1.41 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [18]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python

In [19]:
%timeit?

In [20]:
%%bash
echo "hello world"

hello world


help -> keyboard shortcuts

markdown

$\newcommand{\answers}                             {Y} $
$\newcommand{\realNumbers}                 {\mathbb{R}}$
### types of supervised learning(answers)
**Classification**<br>
$|\answers| < \inf$
* $|\answers| = \{+1,−1\}$ − binary classification
* $|\answers| = \{1,…,K\}$ − classification into $K$ non overlap classes
* $|\answers| = \{0,1\}^K$ − classification into classes that may overlap

**Regression (recovery)**<br>
$|\answers| = \realNumbers^m$ where $m \geq 1$ 

There is one more type if $𝑌$ - infinite ordered set. Task is called ranking, it can be set as supervised learning or unsupervised learning.

http://jupyter.org/documentation a lot of more features, for example widgets

# numpy

In [21]:
import numpy as np
# from python list
x = np.array([1, 2, 3, 5, 4], dtype=np.int32)

In [22]:
x

array([1, 2, 3, 5, 4], dtype=int32)

In [23]:
x.dtype

dtype('int32')

In [24]:
#type
np.int

int

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros([10, 10], dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [27]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.full((3, 5), 2018)

array([[2018, 2018, 2018, 2018, 2018],
       [2018, 2018, 2018, 2018, 2018],
       [2018, 2018, 2018, 2018, 2018]])

In [29]:
np.arange(19, 0 , -2)

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [30]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [32]:
# “continuous uniform” distribution
np.random.random((2, 3))

array([[0.15711259, 0.99906985, 0.58361268],
       [0.28249993, 0.62308934, 0.75559556]])

In [33]:
# normal (Gaussian) distribution
np.random.normal(0, 1, (2, 3))

array([[ 0.55404873, -1.09720055, -0.20204298],
       [-0.15285861,  0.46371096,  0.78477199]])

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
help(np.eye)

Help on function eye in module numpy.lib.twodim_base:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
  

In [34]:
help(np.dot)

Help on built-in function dot in module numpy.core.multiarray:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Se

In [35]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

### index

In [36]:
x[3]

4

from the end

In [37]:
x[-1], x[-3]

(0, 8)

In [35]:
x = np.random.randint(10, size = (3, 4))

In [36]:
x

array([[2, 8, 8, 9],
       [9, 9, 4, 9],
       [2, 4, 9, 4]])

In [37]:
x[0, 0]

2

In [38]:
x[0, 2]

8

In [39]:
x[-1, -1]

4

In [40]:
x[0, 0] = 11

In [41]:
x

array([[11,  8,  8,  9],
       [ 9,  9,  4,  9],
       [ 2,  4,  9,  4]])

In [42]:
x2 = x

In [43]:
x2[0, 0] = 13

In [44]:
print(x)
print(x2)

[[13  8  8  9]
 [ 9  9  4  9]
 [ 2  4  9  4]]
[[13  8  8  9]
 [ 9  9  4  9]
 [ 2  4  9  4]]


In [46]:
x_3 = x.copy()
x_3[0, 0] = 1333

In [48]:
print(x)
print(x2)
print(x_3)

[[13  8  8  9]
 [ 9  9  4  9]
 [ 2  4  9  4]]
[[13  8  8  9]
 [ 9  9  4  9]
 [ 2  4  9  4]]
[[1333    8    8    9]
 [   9    9    4    9]
 [   2    4    9    4]]


### subarrays (slice)

In [49]:
x = np.arange(10)

In [50]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [51]:
x[:5]

array([0, 1, 2, 3, 4])

In [52]:
x[5:]

array([5, 6, 7, 8, 9])

In [53]:
x[5:-1]

array([5, 6, 7, 8])

In [54]:
x[4:7]

array([4, 5, 6])

In [55]:
x[::2]

array([0, 2, 4, 6, 8])

In [56]:
x[3:-1:3]

array([3, 6])

In [57]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

start, end, step

In [58]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

_**reshape**_

In [59]:
x = x.reshape((3, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
x = x.reshape((2, 3, 2))
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [61]:
x = x.reshape((12, ))
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
x = x.reshape((3, 4))
x[:2, :3] = np.ones((2, 3))

In [63]:
x

array([[ 1,  1,  1,  3],
       [ 1,  1,  1,  7],
       [ 8,  9, 10, 11]])

In [64]:
x_p = list(x)

In [67]:
x[::-1, :-1:]

array([[ 8,  9, 10],
       [ 1,  1,  1],
       [ 1,  1,  1]])

slice $=$ views<br>
slice $\neq$ copies

In [70]:
x[:2, :2] = np.eye(2)*1333

In [71]:
print(x)

[[1333    0    1    3]
 [   0 1333    1    7]
 [   8    9   10   11]]


### concatenate

In [72]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [73]:
z = np.concatenate([x, y])
print(z)

[1 2 3 4 5 6]


In [74]:
g = np.array([[1, 2, 3],
              [4, 5, 6]])

In [75]:
print(g)

[[1 2 3]
 [4 5 6]]


In [76]:
np.concatenate([g, g])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [77]:
np.concatenate([g, g], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [78]:
np.vstack([x, g])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [79]:
np.hstack([g, x[:-1].reshape([2, 1])])

array([[1, 2, 3, 1],
       [4, 5, 6, 2]])

### calculations on arrays

In [80]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
x + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
x - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [83]:
2 ** x

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

In [84]:
x / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [85]:
y = np.arange(10, 20)
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [86]:
x - y

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [87]:
x + y

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [88]:
x / y

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [89]:
x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
x * x

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [91]:
#matrix multiplication
np.dot(x, x)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [92]:
x = x.reshape((9,))
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [93]:
x.sum()

36

In [94]:
np.add.reduce(x)

36

In [95]:
np.multiply.reduce(x + 1)

362880

In [96]:
np.add.accumulate(x)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [97]:
x = x ** 2 - 4 * x + 1
x

array([ 1, -2, -3, -2,  1,  6, 13, 22, 33])

In [98]:
x.max(), x.argmax(), x.min(), x.argmin()

(33, 8, -3, 2)

### masks

In [99]:
x > 0

array([ True, False, False, False,  True,  True,  True,  True,  True])

In [100]:
x[x > 0]

array([ 1,  1,  6, 13, 22, 33])

In [101]:
x[(x > 0) & (x < 10)] # and

array([1, 1, 6])

In [102]:
x[(x > 10) | (x < 0)] # or

array([-2, -3, -2, 13, 22, 33])

In [103]:
x[~(x > 10)] #not

array([ 1, -2, -3, -2,  1,  6])

 https://docs.scipy.org/doc/numpy/user/index.html

# Pandas

In [104]:
import pandas as pd

In [105]:
data = pd.Series([1, 2, 3, 4.5])

In [106]:
data.values

array([1. , 2. , 3. , 4.5])

np.array

In [107]:
data

0    1.0
1    2.0
2    3.0
3    4.5
dtype: float64

In [108]:
dict_ = {'a' : 23,
         'qwerty' : 12345,
         'phi' : 3.14, 
         'values smth':20}

x = pd.Series(dict_)

In [111]:
x['values smth']

20.0

In [112]:
x['phi'] 

3.14

In [113]:
x.phi

3.14

In [114]:
data = pd.read_csv("dataregression.csv")

In [115]:
data

feature_1  feature_2  feature_3     label
0      0.146     -1.157      0.379  0.870982
1      1.286      0.658     -1.769 -3.705259
2     -1.872     -0.426     -0.022 -1.576071
3      0.949      0.958      0.694  3.962416
4     -1.985      0.727      1.181  2.981715
5      0.741     -0.393      0.083  0.862554
6     -1.194     -1.970     -1.347 -6.187324
7      1.474      0.899     -1.009 -0.975111
8      0.193     -0.171      0.072  0.505087
9     -0.643     -2.255      1.427  2.423583

In [116]:
data.values #np

array([[ 0.146     , -1.157     ,  0.379     ,  0.87098153],
       [ 1.286     ,  0.658     , -1.769     , -3.70525948],
       [-1.872     , -0.426     , -0.022     , -1.57607053],
       [ 0.949     ,  0.958     ,  0.694     ,  3.96241584],
       [-1.985     ,  0.727     ,  1.181     ,  2.9817153 ],
       [ 0.741     , -0.393     ,  0.083     ,  0.86255406],
       [-1.194     , -1.97      , -1.347     , -6.18732382],
       [ 1.474     ,  0.899     , -1.009     , -0.97511125],
       [ 0.193     , -0.171     ,  0.072     ,  0.50508739],
       [-0.643     , -2.255     ,  1.427     ,  2.42358325]])

In [117]:
data.head()

feature_1  feature_2  feature_3     label
0      0.146     -1.157      0.379  0.870982
1      1.286      0.658     -1.769 -3.705259
2     -1.872     -0.426     -0.022 -1.576071
3      0.949      0.958      0.694  3.962416
4     -1.985      0.727      1.181  2.981715

In [118]:
data.head(3)

feature_1  feature_2  feature_3     label
0      0.146     -1.157      0.379  0.870982
1      1.286      0.658     -1.769 -3.705259
2     -1.872     -0.426     -0.022 -1.576071

In [119]:
data.tail(3)

feature_1  feature_2  feature_3     label
7      1.474      0.899     -1.009 -0.975111
8      0.193     -0.171      0.072  0.505087
9     -0.643     -2.255      1.427  2.423583

In [120]:
indexes = ["object_" + str(i) for i in range(10)]

In [121]:
data.index = indexes

In [122]:
data

feature_1  feature_2  feature_3     label
object_0      0.146     -1.157      0.379  0.870982
object_1      1.286      0.658     -1.769 -3.705259
object_2     -1.872     -0.426     -0.022 -1.576071
object_3      0.949      0.958      0.694  3.962416
object_4     -1.985      0.727      1.181  2.981715
object_5      0.741     -0.393      0.083  0.862554
object_6     -1.194     -1.970     -1.347 -6.187324
object_7      1.474      0.899     -1.009 -0.975111
object_8      0.193     -0.171      0.072  0.505087
object_9     -0.643     -2.255      1.427  2.423583

In [123]:
data.columns

Index(['feature_1', 'feature_2', 'feature_3', 'label'], dtype='object')

In [124]:
data.columns.values[-1] = 'Y'

In [125]:
data.head()

feature_1  feature_2  feature_3         Y
object_0      0.146     -1.157      0.379  0.870982
object_1      1.286      0.658     -1.769 -3.705259
object_2     -1.872     -0.426     -0.022 -1.576071
object_3      0.949      0.958      0.694  3.962416
object_4     -1.985      0.727      1.181  2.981715

In [126]:
#data.loc['object_1':'object_3']

In [127]:
#data.loc['object_1':'object_3', 'feature_2':]

In [128]:
data.iloc[1:-1, :-1]

feature_1  feature_2  feature_3
object_1      1.286      0.658     -1.769
object_2     -1.872     -0.426     -0.022
object_3      0.949      0.958      0.694
object_4     -1.985      0.727      1.181
object_5      0.741     -0.393      0.083
object_6     -1.194     -1.970     -1.347
object_7      1.474      0.899     -1.009
object_8      0.193     -0.171      0.072

In [129]:
data.values

array([[ 0.146     , -1.157     ,  0.379     ,  0.87098153],
       [ 1.286     ,  0.658     , -1.769     , -3.70525948],
       [-1.872     , -0.426     , -0.022     , -1.57607053],
       [ 0.949     ,  0.958     ,  0.694     ,  3.96241584],
       [-1.985     ,  0.727     ,  1.181     ,  2.9817153 ],
       [ 0.741     , -0.393     ,  0.083     ,  0.86255406],
       [-1.194     , -1.97      , -1.347     , -6.18732382],
       [ 1.474     ,  0.899     , -1.009     , -0.97511125],
       [ 0.193     , -0.171     ,  0.072     ,  0.50508739],
       [-0.643     , -2.255     ,  1.427     ,  2.42358325]])

In [130]:
data.values[0, 0] = 0.01

In [131]:
data

feature_1  feature_2  feature_3         Y
object_0      0.010     -1.157      0.379  0.870982
object_1      1.286      0.658     -1.769 -3.705259
object_2     -1.872     -0.426     -0.022 -1.576071
object_3      0.949      0.958      0.694  3.962416
object_4     -1.985      0.727      1.181  2.981715
object_5      0.741     -0.393      0.083  0.862554
object_6     -1.194     -1.970     -1.347 -6.187324
object_7      1.474      0.899     -1.009 -0.975111
object_8      0.193     -0.171      0.072  0.505087
object_9     -0.643     -2.255      1.427  2.423583

In [132]:
sex = ['m' if x == 1 else 'w' for x in np.random.randint(2, size = 10)]
sex

['m', 'm', 'm', 'm', 'w', 'w', 'w', 'm', 'm', 'm']

In [133]:
data['sex'] = sex

In [134]:
data

feature_1  feature_2  feature_3         Y sex
object_0      0.010     -1.157      0.379  0.870982   m
object_1      1.286      0.658     -1.769 -3.705259   m
object_2     -1.872     -0.426     -0.022 -1.576071   m
object_3      0.949      0.958      0.694  3.962416   m
object_4     -1.985      0.727      1.181  2.981715   w
object_5      0.741     -0.393      0.083  0.862554   w
object_6     -1.194     -1.970     -1.347 -6.187324   w
object_7      1.474      0.899     -1.009 -0.975111   m
object_8      0.193     -0.171      0.072  0.505087   m
object_9     -0.643     -2.255      1.427  2.423583   m

In [ ]:
data.values

In [ ]:
data.sex

In [ ]:
data[(data.sex == 'm') & (data['Y'] > 0)] #do not forget the brackets

In [ ]:
data['sum'] = data.iloc[:, :-2].sum(axis = 1)

In [ ]:
data.head(3)

In [ ]:
data = data.iloc[1:, :]
data

In [ ]:
data = data.iloc[:, 1:]
data

In [ ]:
data['sum'] = data.iloc[:, :-3].sum(axis = 1)
data

In [ ]:
data = data.loc[:, ('feature_2', 'feature_3', 'sex', 'sum', 'Y')]
data

In [ ]:
%matplotlib inline

In [ ]:
data.Y.hist(bins = 3)

http://pandas.pydata.org/pandas-docs/stable/

# Matplotlib

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
x = np.random.random(size = 1000)

In [ ]:
plt.plot(x)

In [ ]:
plt.plot(x, '.')

In [ ]:
plt.hist(x)

In [ ]:
x = np.random.normal(scale=0.3, size=1000)
plt.plot(x, '.')

In [ ]:
plt.hist(x)

In [ ]:
x = np.linspace(0, 10, 100)

plt.plot(x, np.sin(x))
plt.plot(x, np.cos(x))

plt.show()

In [ ]:
plt.plot(x, np.sin(x), color = 'g', linestyle='-.')
plt.plot(x, np.cos(x), color = [1, 0, 0], linestyle='--')

plt.show()

In [ ]:
plt.figure() # image for several plots

plt.subplot(2, 1, 1) # (rows, columns, panel number)
plt.plot(x, np.sin(x))

plt.subplot(2, 1, 2)
plt.plot(x, np.cos(x), '.')

In [ ]:
plt.plot(x, np.sin(x), color = 'g', linestyle='-.', label="sin(x)")
plt.plot(x, np.cos(x), color = [1, 0, 0], linestyle='--', label="cos(x)")

plt.legend()

plt.title("trigonometric functions")

plt.xlabel("x")
plt.ylabel("y")

plt.savefig('result.png')

plt.show()

In [ ]:
image = plt.imread("result.png")
plt.imshow(image)

In [ ]:
x1 = np.random.normal(1, 1, 10000)
x2 = np.random.normal(-1, 1, 10000)

plt.hist(x1, color = 'g', alpha = 0.5, bins=100)
plt.hist(x2, color = 'r', alpha = 0.5, bins=100)

plt.show()

### 3d visualisation

In [ ]:
def f(x, y):
    return np.sin(x) + np.cos(y)

In [ ]:
x = np.linspace(0, 2*np.pi, 1000)
X, Y = np.meshgrid(x, x)

In [ ]:
help(np.meshgrid)

In [ ]:
Z = f(X, Y)
plt.style.use('seaborn-white')
plt.contourf(X, Y, Z, cmap='RdGy')#red gray

https://matplotlib.org/ and https://seaborn.pydata.org/